title: Graham Twaddle
description: Professional presence for Graham Twaddle, a knowledge and information management consultant and technology enthusiast.
url: https://rococo-capybara-027c73.netlify.app
