# Sveltia CMS configuration

backend:
  name: github
  repo: word2web/eleventy-sveltia-cms-starter
  branch: master

media_folder: "assets/img"

collections:
  - name: "blog"
    label: "Posts"
    label_singular: "Post"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Author", name: "author", widget: "relation", collection: "authors", value_field: "name" }
      - { label: "Summary", name: "summary", widget: "text" }
      - { label: "Tags", name: "tags", widget: "list", default: ["post"], hint: "Enter tags separated by a comma" }
      - label: "Image"
        name: "image"
        widget: "image"
        required: false
        hint: "Upload an image for this post. You can also use an image URL."
      - { label: "Image Alt Text", name: "imageAltText", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "pages"
    label: "Pages"
    label_singular: "Page"
    folder: "pages"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Permalink", name: "permalink", widget: "hidden" }
      - label: "Navigation"
        name: "eleventyNavigation"
        widget: "object"
        fields:
          - { label: "Key", name: "key", widget: "string" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Order", name: "order", widget: "number", default: 999 }
          - { label: "Exclude from Navigation", name: "nav_exclude", widget: "boolean", default: false }
  - name: "authors"
    label: "Authors"
    label_singular: "Author"
    icon: "person"
    folder: "authors"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - label: "Image"
        name: "image"
        widget: "image"
        media_library:
          config:
            max_file_size: 1024000
      - { label: "Description", name: "body", widget: "markdown" }
  - name: "settings"
    label: "Settings"
    icon: "settings"
    extension: "yml"
    format: "yml"
    files:
      - file: "_data/settings.yml"
        label: "Site Settings"
        name: "site"
        fields:
          - { label: "Site Title", name: "title", widget: "string" }
          - { label: "Site Description", name: "description", widget: "text" }
          - { label: "Site URL", name: "url", widget: "string" }